### ISSUE TITLE
Wrong parsing of file path on Windows

### ISSUE THREAD

**Issue by sSwSs** [christopherbradleybanks/eslint-plugin-folders#1]
Currently plugin isn't working on windows systems because path separator is '\\' instead of '/'. 

To fix it on my local env I need to change code to looks like that:
`const dir = parsed.dir.split('\\').join('/')`
`const [,relativePath] = dir.split(root)`

But I'm pretty sure that there is more clear way to fix it

**Comment by christopherbradleybanks** [comment]
> Currently plugin isn't working on windows systems because path separator is '' instead of '/'.
> 
> To fix it on my local env I need to change code to looks like that:
> `const dir = parsed.dir.split('\\').join('/')`
> `const [,relativePath] = dir.split(root)`
> 
> But I'm pretty sure that there is more clear way to fix it

Thanks for the heads up I will look into it and resolve

**Comment by Aaronius** [comment]
FYI, this issue is a blocker for us. I haven't looked into the issue as much as @sSwSs, but https://nodejs.org/api/path.html#pathsep may help here. @sSwSs, did you end up using your modified version or did you find a different eslint plugin to use?

**Comment by sSwSs** [comment]
@Aaronius It looks like this is the only plugin that fits my requirements, so I am using with my modified version. As for now everything is working fine. (on windows dev env and linux CI/CD)

**Comment by stephenscholz** [comment]
I just included the backslashes in my regex. This gives me good results for the kebab-case folder structure i use.
This is one example i use: `'folders/match-regex': ['error', '^[a-z0-9-\\\\]+$', /src.+src/],`

**Comment by christopherbradleybanks** [comment]
Happy to review a pull request to address this issue

**Comment by Laffery** [comment]
How about use `path.posix.sep` instead?
```diff
- relativePath.split(`\/`).forEach((directory) => {
+ relativePath.split(path.posix.sep).forEach((directory) => {
```
