### ISSUE TITLE
Regex.test error

### ISSUE THREAD

**Issue by KumaCool** [christopherbradleybanks/eslint-plugin-folders#2]
https://github.com/christopherbradleybanks/eslint-plugin-folders/blob/c6f564033e4ee15bcdbc3d816f5e6459980b980a/lib/rules/match-regex.js#L19

Unexpected results due to subscript movement when `Regex.test` is executed multiple times in `g` mode

**Comment by christopherbradleybanks** [comment]
> https://github.com/christopherbradleybanks/eslint-plugin-folders/blob/c6f564033e4ee15bcdbc3d816f5e6459980b980a/lib/rules/match-regex.js#L19
> 
> Unexpected results due to subscript movement when `Regex.test` is executed multiple times in `g` mode

this should be resolved now
